/*
====================================================================================================
Cartiglio Narrativo di Sviluppo SQL - Standard SOLVERIS
====================================================================================================
Data e Ora di Modifica : 23/09/2026 15:55
Autore                  : SOLVERIS - Bandera Marco
Progetto                : TMV - Correzione Strutturale Vista di Frontiera Batch ImpExp TMV-LPM
Oggetto SQL             : Vista dbo.VPRT_CERTIFICATI_CLONA_B7
Nome File               : VPRT_CERTIFICATI_CLONA_B7.sql
Ambiente Database       : DBTMV (MSSQL 14.0.2120.1 - SQL Server 2017)
----------------------------------------------------------------------------------------------------
DESCRIZIONE AD ALTISSIMO DETTAGLIO ED OBIETTIVO DI BUSINESS:
La vista 'VPRT_CERTIFICATI_CLONA_B7' costituisce la sorgente dati primaria per la pipeline batch
ImpExp 'TMV-LPM', deputata alla clonazione e avanzamento a terzista (L.P.M. SNC DI MOLINARI VINCENZO
& C. - Fornitore 147) del materiale in ingresso contraddistinto da codifica 'TD%' con lega speciale
B7 ('B7-' o 'B7M').

PIPELINE BATCH ASSOCIATA (INSIEME 'TMV-LPM'):
1. Passaggio 1 (Tracciato 'TMV-LPM'):
   Filtra le righe con 'DO30_DITTA_CG18_OCLP IS NULL' ed emette l'Ordine di Conto Lavoro Passivo
   'DF-ORDINECLP' intestato a LPM (fornitore 147), creando il vincolo di storno in DO33 verso il DDT.
2. Passaggio 2 (Tracciato 'TMV-LPM-CLAINV'):
   Emette il DDT di invio merce a LPM ('DF-DDTCLAVINV').
3. Passaggi 3 e 4 (Tracciati 'TMV-LPM-CLACAR' e 'TMV-LPM-CLACAR3'):
   Generano e perfezionano il DDT di rientro da LPM ('DF-DDTCLAVCAR') trasformando l'articolo da B7 a L7.

MOTIVAZIONE DELLA MODIFICA STRUTTURALE (Rev. 2.0):
Nel tracciato ImpExp 'TMV-LPM', la differenziazione tra:
  - Creazione di una NUOVA riga di corpo documento ('DO30')
  - e semplice AGGIUNTA di un lotto ulteriore ('DO52') alla medesima riga
è rigidamente governata dalla condizione di stacco riga:
  [Progressivo_dettaglio_corpo] = 1  --> Nuova riga DO30
  [Progressivo_dettaglio_corpo] > 1  --> Dettaglio lotto aggiuntivo (senza nuova riga DO30)

Poiché il campo [Progressivo_dettaglio_corpo] era mappato sulla colonna raw 'DO52_PROG' della vista,
qualora in Gamma Enterprise un documento di carico 'DF-DDT' multi-riga o multi-lotto contenesse una riga
il cui primo lotto non partiva da 1 (es. progressivo documento continuato a 2, 3... come avvenuto per
la riga 4 del DDT 709 del 20/04/2026), il motore batch interpretava erroneamente tale riga NON come un
nuovo articolo da ordinare, bensì come un lotto secondario della riga precedente!
Di conseguenza, la riga non veniva mai creata in DO30 sull'ordine OCLP, lasciando il materiale orfano.

SOLUZIONE APPLICATA:
La colonna esposta 'DO52_PROG' viene ora calcolata analiticamente tramite la funzione di partizione:
  ROW_NUMBER() OVER (
      PARTITION BY dbo.DO30_DOCCORPO.DO30_DITTA_CG18, 
                   dbo.DO30_DOCCORPO.DO30_NUMREG_CO99, 
                   dbo.DO30_DOCCORPO.DO30_PROGRIGA 
      ORDER BY dbo.DO52_DOCCORPOLOT.DO52_PROG
  ) AS DO52_PROG
Questo garantisce in modo matematico che il primo lotto di QUALSIASI riga documento valga sempre 1,
permettendo al batch 'TMV-LPM' di staccare regolarmente la riga documento indipendentemente da come
l'operatore abbia inserito o numerato i progressivi lotti in magazzino.
----------------------------------------------------------------------------------------------------
STORICO REVISIONI (Change Log Narrativo):
- Rev. 1.0 (Origine): Vista iniziale di estrazione dati per Insieme ImpExp TMV-LPM.
- Rev. 2.0 (23/09/2026 - SOLVERIS - Bandera Marco): 
  Sostituzione del campo esposto DO52_PROG con ROW_NUMBER() per riga documento DO30. Risolto il bug
  strutturale che causava la mancata creazione dell'OCLP in presenza di lotti con progressivo iniziale > 1
  (es. DDT 709 riga 4).
====================================================================================================
*/

ALTER VIEW dbo.VPRT_CERTIFICATI_CLONA_B7
AS
SELECT DISTINCT 
    TOP (100) PERCENT 
    dbo.DO11_DOCTESTATA.DO11_DITTA_CG18, 
    dbo.DO11_DOCTESTATA.DO11_NUMREG_CO99, 
    dbo.DO11_DOCTESTATA.DO11_DOCUM_MG36, 
    dbo.DO11_DOCTESTATA.DO11_NUMDOC, 
    dbo.DO11_DOCTESTATA.DO11_DATADOC, 
    dbo.DO11_DOCTESTATA.DO11_DATAREG, 
    dbo.DO11_DOCTESTATA.DO11_CODDEP, 
    dbo.DO30_DOCCORPO.DO30_DITTA_CG18, 
    dbo.DO30_DOCCORPO.DO30_NUMREG_CO99, 
    dbo.DO30_DOCCORPO.DO30_PROGRIGA, 
    dbo.DO30_DOCCORPO.DO30_PROGVISUASTA, 
    dbo.DO30_DOCCORPO.DO30_CODART_MG66, 
    dbo.DO30_DOCCORPO.DO30_OPZIONE_MG5E, 
    dbo.DO30_DOCCORPO.DO30_UM1, 
    dbo.DO30_DOCCORPO.DO30_UM2, 
    dbo.DO30_DOCCORPO.DO30_QTA1, 
    dbo.DO30_DOCCORPO.DO30_QTA2, 
    dbo.DO30_DOCCORPO.DO30_DESCART, 
    dbo.DO30_DOCCORPO.DO30_DESCARTL, 
    dbo.DO30_DOCCORPO.DO30_ESTDESCART, 
    dbo.DO30_DOCCORPO.DO30_ESTDESCARTL, 
    dbo.DO52_DOCCORPOLOT.DO52_CODLOTTO_MG4G, 
    dbo.MG4G_ANAGRLOTTI.MG4G_DESCLOTTO, 
    dbo.CO5L_ATTRIBUTIDEN.CO5L_GUID, 
    dbo.CO5L_ATTRIBUTIDEN.CO5L_DATA1, 
    dbo.DO52_DOCCORPOLOT.DO52_QTA1, 
    dbo.DO52_DOCCORPOLOT.DO52_QTA2, 
    ROW_NUMBER() OVER (
        PARTITION BY dbo.DO30_DOCCORPO.DO30_DITTA_CG18, 
                     dbo.DO30_DOCCORPO.DO30_NUMREG_CO99, 
                     dbo.DO30_DOCCORPO.DO30_PROGRIGA 
        ORDER BY dbo.DO52_DOCCORPOLOT.DO52_PROG
    ) AS DO52_PROG, 
    ESTREMI_DF_ORDINECLP.DO30_DITTA_CG18 AS DO30_DITTA_CG18_OCLP, 
    ESTREMI_DF_ORDINECLP.DO30_NUMREG_CO99 AS DO30_NUMREG_CO99_OCLP, 
    ESTREMI_DF_ORDINECLP.DO30_PROGRIGA AS DO30_PROGRIGA_OCLP, 
    ESTREMI_DF_ORDINECLP.DO30_QTA1 AS DO30_QTA1_OCLP, 
    ESTREMI_DF_ORDINECLP.DO30_QTA2 AS DO30_QTA2_OCLP, 
    ESTREMI_DF_ORDINECLP.DO52_CODLOTTO_MG4G AS DO52_CODLOTTO_MG4G_OCLP, 
    ESTREMI_DF_ORDINECLP.DO52_QTA1 AS DO52_QTA1_OCLP, 
    ESTREMI_DF_ORDINECLP.DO52_QTA2 AS DO52_QTA2_OCLP, 
    ESTREMI_DF_ORDINECLP.DO11_NUMDOC AS DO11_NUMDOC_OCLP, 
    ESTREMI_DF_ORDINECLP.DO52_PROG AS DO52_PROG_OCLP, 
    ESTREMI_DF_DDTCLAINV.DO30_DITTA_CG18 AS DO30_DITTA_CG18_CLAINV, 
    ESTREMI_DF_DDTCLAINV.DO30_NUMREG_CO99 AS DO30_NUMREG_CO99_CLAINV, 
    ESTREMI_DF_DDTCLAINV.DO30_PROGRIGA AS DO30_PROGRIGA_CLAINV, 
    ESTREMI_DF_DDTCLAINV.DO30_QTA1 AS DO30_QTA1_CLAINV, 
    ESTREMI_DF_DDTCLAINV.DO30_QTA2 AS DO30_QTA2_CLAINV, 
    ESTREMI_DF_DDTCLAINV.DO52_CODLOTTO_MG4G AS DO52_CODLOTTO_MG4G_CLAINV, 
    ESTREMI_DF_DDTCLAINV.DO52_QTA1 AS DO52_QTA1_CLAINV, 
    ESTREMI_DF_DDTCLAINV.DO52_QTA2 AS DO52_QTA2_CLAINV, 
    ESTREMI_DF_DDTCLAINV.DO11_NUMDOC AS DO11_NUMDOC_CLAINV, 
    ESTREMI_DF_DDTCLAINV.DO52_PROG AS DO52_PROG_CLAINV, 
    DATEADD(dd, 1, ESTREMI_DF_DDTCLAINV.DO11_DATADOC) AS DO11_NEW_DATADOC_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO30_DITTA_CG18 AS DO30_DITTA_CG18_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO30_NUMREG_CO99 AS DO30_NUMREG_CO99_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO30_PROGRIGA AS DO30_PROGRIGA_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO30_QTA1 AS DO30_QTA1_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO30_QTA2 AS DO30_QTA2_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO52_CODLOTTO_MG4G AS DO52_CODLOTTO_MG4G_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO52_QTA1 AS DO52_QTA1_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO52_QTA2 AS DO52_QTA2_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO11_NUMDOC AS DO11_NUMDOC_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO52_PROG AS DO52_PROG_CLACAR, 
    ISNULL(ESTREMI_DF_DDTCLACAR.DO11_FLGESTRATTO, 0) AS DO11_FLGESTRATTO_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO11_SEZDOC AS DO11_SEZDOC_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO11_ANNODOC AS DO11_ANNODOC_CLACAR, 
    ESTREMI_DF_DDTCLACAR.DO11_DATADOC AS DO11_DATADOC_CLACAR, 
    ESTREMI_DF_ORDINECLP.DO11_DATADOC AS DO11_DATADOC_OCLP, 
    ESTREMI_DF_ORDINECLP.DO11_DATAREG AS DO11_DATAREG_OCLP, 
    ESTREMI_DF_DDTCLAINV.DO11_DATADOC AS DO11_DATADOC_CLAINV, 
    ESTREMI_DF_DDTCLAINV.DO11_DATAREG AS DO11_DATAREG_CLAINV, 
    ESTREMI_DF_DDTCLACAR.DO11_DATAREG AS DO11_DATAREG_CLACAR
FROM dbo.DO11_DOCTESTATA 
INNER JOIN dbo.DO30_DOCCORPO 
    ON dbo.DO11_DOCTESTATA.DO11_DITTA_CG18 = dbo.DO30_DOCCORPO.DO30_DITTA_CG18 
    AND dbo.DO11_DOCTESTATA.DO11_NUMREG_CO99 = dbo.DO30_DOCCORPO.DO30_NUMREG_CO99 
INNER JOIN dbo.DO52_DOCCORPOLOT 
    ON dbo.DO30_DOCCORPO.DO30_DITTA_CG18 = dbo.DO52_DOCCORPOLOT.DO52_DITTA_CG18 
    AND dbo.DO30_DOCCORPO.DO30_NUMREG_CO99 = dbo.DO52_DOCCORPOLOT.DO52_NUMREG_CO99 
    AND dbo.DO30_DOCCORPO.DO30_PROGRIGA = dbo.DO52_DOCCORPOLOT.DO52_PROGRIGA 
INNER JOIN dbo.MG4G_ANAGRLOTTI 
    ON dbo.DO52_DOCCORPOLOT.DO52_DITTA_CG18 = dbo.MG4G_ANAGRLOTTI.MG4G_DITTA_CG18 
    AND dbo.DO52_DOCCORPOLOT.DO52_DITTA_CG18 = dbo.MG4G_ANAGRLOTTI.MG4G_DITTA_CG18 
    AND dbo.DO52_DOCCORPOLOT.DO52_CODART_MG66 = dbo.MG4G_ANAGRLOTTI.MG4G_CODART_MG66 
    AND dbo.DO52_DOCCORPOLOT.DO52_OPZIONE_MG5E = dbo.MG4G_ANAGRLOTTI.MG4G_OPZIONE_MG5E 
    AND dbo.DO52_DOCCORPOLOT.DO52_CODLOTTO_MG4G = dbo.MG4G_ANAGRLOTTI.MG4G_CODLOTTO 
INNER JOIN dbo.CO5L_ATTRIBUTIDEN 
    ON dbo.MG4G_ANAGRLOTTI.MG4G_GUID = dbo.CO5L_ATTRIBUTIDEN.CO5L_GUID 
LEFT OUTER JOIN (
    SELECT DISTINCT 
        DO11_DOCTESTATA_3.DO11_DATADOC, DO11_DOCTESTATA_3.DO11_DATAREG, 
        DO30_DOCCORPO_3.DO30_DITTA_CG18, DO30_DOCCORPO_3.DO30_NUMREG_CO99, DO30_DOCCORPO_3.DO30_PROGRIGA, 
        DO30_DOCCORPO_3.DO30_QTA1, DO30_DOCCORPO_3.DO30_QTA2, 
        DO52_DOCCORPOLOT_3.DO52_CODLOTTO_MG4G, DO52_DOCCORPOLOT_3.DO52_QTA1, DO52_DOCCORPOLOT_3.DO52_QTA2, 
        DO11_DOCTESTATA_3.DO11_NUMDOC, DO52_DOCCORPOLOT_3.DO52_PROG, 
        dbo.DO33_DOCCORPORIF.DO33_DITTA_CG18, dbo.DO33_DOCCORPORIF.DO33_NUMREGRIF_CO99, 
        dbo.DO33_DOCCORPORIF.DO33_PROGRIGARIF_DO30
    FROM dbo.DO33_DOCCORPORIF 
    INNER JOIN dbo.DO30_DOCCORPO AS DO30_DOCCORPO_3 
        ON dbo.DO33_DOCCORPORIF.DO33_DITTA_CG18 = DO30_DOCCORPO_3.DO30_DITTA_CG18 
        AND dbo.DO33_DOCCORPORIF.DO33_NUMREG_CO99 = DO30_DOCCORPO_3.DO30_NUMREG_CO99 
        AND dbo.DO33_DOCCORPORIF.DO33_PROGRIGA = DO30_DOCCORPO_3.DO30_PROGRIGA 
        AND dbo.DO33_DOCCORPORIF.DO33_PROGRIF = 1 
    INNER JOIN dbo.DO11_DOCTESTATA AS DO11_DOCTESTATA_3 
        ON DO30_DOCCORPO_3.DO30_DITTA_CG18 = DO11_DOCTESTATA_3.DO11_DITTA_CG18 
        AND DO30_DOCCORPO_3.DO30_NUMREG_CO99 = DO11_DOCTESTATA_3.DO11_NUMREG_CO99 
    INNER JOIN dbo.DO52_DOCCORPOLOT AS DO52_DOCCORPOLOT_3 
        ON DO30_DOCCORPO_3.DO30_DITTA_CG18 = DO52_DOCCORPOLOT_3.DO52_DITTA_CG18 
        AND DO30_DOCCORPO_3.DO30_NUMREG_CO99 = DO52_DOCCORPOLOT_3.DO52_NUMREG_CO99 
        AND DO30_DOCCORPO_3.DO30_PROGRIGA = DO52_DOCCORPOLOT_3.DO52_PROGRIGA
    WHERE (DO11_DOCTESTATA_3.DO11_DOCUM_MG36 = 'DF-ORDINECLP')
) AS ESTREMI_DF_ORDINECLP 
    ON dbo.DO30_DOCCORPO.DO30_DITTA_CG18 = ESTREMI_DF_ORDINECLP.DO33_DITTA_CG18 
    AND dbo.DO30_DOCCORPO.DO30_NUMREG_CO99 = ESTREMI_DF_ORDINECLP.DO33_NUMREGRIF_CO99 
    AND dbo.DO30_DOCCORPO.DO30_PROGRIGA = ESTREMI_DF_ORDINECLP.DO33_PROGRIGARIF_DO30 
    AND dbo.DO52_DOCCORPOLOT.DO52_PROG = ESTREMI_DF_ORDINECLP.DO52_PROG 
LEFT OUTER JOIN (
    SELECT DISTINCT 
        DO30_DOCCORPO_2.DO30_DITTA_CG18, DO30_DOCCORPO_2.DO30_NUMREG_CO99, DO30_DOCCORPO_2.DO30_PROGRIGA, 
        DO30_DOCCORPO_2.DO30_QTA1, DO30_DOCCORPO_2.DO30_QTA2, 
        DO52_DOCCORPOLOT_2.DO52_CODLOTTO_MG4G, DO52_DOCCORPOLOT_2.DO52_QTA1, DO52_DOCCORPOLOT_2.DO52_QTA2, 
        DO11_DOCTESTATA_2.DO11_NUMDOC, DO52_DOCCORPOLOT_2.DO52_PROG, 
        DO33_DOCCORPORIF_2.DO33_DITTA_CG18, DO33_DOCCORPORIF_2.DO33_NUMREGRIF_CO99, 
        DO33_DOCCORPORIF_2.DO33_PROGRIGARIF_DO30, DO11_DOCTESTATA_2.DO11_DATADOC, DO11_DOCTESTATA_2.DO11_DATAREG
    FROM dbo.DO33_DOCCORPORIF AS DO33_DOCCORPORIF_2 
    INNER JOIN dbo.DO30_DOCCORPO AS DO30_DOCCORPO_2 
        ON DO33_DOCCORPORIF_2.DO33_DITTA_CG18 = DO30_DOCCORPO_2.DO30_DITTA_CG18 
        AND DO33_DOCCORPORIF_2.DO33_NUMREG_CO99 = DO30_DOCCORPO_2.DO30_NUMREG_CO99 
        AND DO33_DOCCORPORIF_2.DO33_PROGRIGA = DO30_DOCCORPO_2.DO30_PROGRIGA 
        AND DO33_DOCCORPORIF_2.DO33_PROGRIF = 1 
    INNER JOIN dbo.DO11_DOCTESTATA AS DO11_DOCTESTATA_2 
        ON DO30_DOCCORPO_2.DO30_DITTA_CG18 = DO11_DOCTESTATA_2.DO11_DITTA_CG18 
        AND DO30_DOCCORPO_2.DO30_NUMREG_CO99 = DO11_DOCTESTATA_2.DO11_NUMREG_CO99 
    INNER JOIN dbo.DO52_DOCCORPOLOT AS DO52_DOCCORPOLOT_2 
        ON DO30_DOCCORPO_2.DO30_DITTA_CG18 = DO52_DOCCORPOLOT_2.DO52_DITTA_CG18 
        AND DO30_DOCCORPO_2.DO30_NUMREG_CO99 = DO52_DOCCORPOLOT_2.DO52_NUMREG_CO99 
        AND DO30_DOCCORPO_2.DO30_PROGRIGA = DO52_DOCCORPOLOT_2.DO52_PROGRIGA
    WHERE (DO11_DOCTESTATA_2.DO11_DOCUM_MG36 = 'DF-DDTCLAVINV')
) AS ESTREMI_DF_DDTCLAINV 
    ON ESTREMI_DF_ORDINECLP.DO30_DITTA_CG18 = ESTREMI_DF_DDTCLAINV.DO33_DITTA_CG18 
    AND ESTREMI_DF_ORDINECLP.DO30_NUMREG_CO99 = ESTREMI_DF_DDTCLAINV.DO33_NUMREGRIF_CO99 
    AND ESTREMI_DF_ORDINECLP.DO30_PROGRIGA = ESTREMI_DF_DDTCLAINV.DO33_PROGRIGARIF_DO30 
    AND ESTREMI_DF_ORDINECLP.DO52_PROG = ESTREMI_DF_DDTCLAINV.DO52_PROG 
LEFT OUTER JOIN (
    SELECT DISTINCT 
        DO30_DOCCORPO_1.DO30_DITTA_CG18, DO30_DOCCORPO_1.DO30_NUMREG_CO99, DO30_DOCCORPO_1.DO30_PROGRIGA, 
        DO30_DOCCORPO_1.DO30_QTA1, DO30_DOCCORPO_1.DO30_QTA2, 
        DO52_DOCCORPOLOT_1.DO52_CODLOTTO_MG4G, DO52_DOCCORPOLOT_1.DO52_QTA1, DO52_DOCCORPOLOT_1.DO52_QTA2, 
        DO11_DOCTESTATA_1.DO11_NUMDOC, DO52_DOCCORPOLOT_1.DO52_PROG, 
        DO33_DOCCORPORIF_1.DO33_DITTA_CG18, DO33_DOCCORPORIF_1.DO33_NUMREGRIF_CO99, 
        DO33_DOCCORPORIF_1.DO33_PROGRIGARIF_DO30, DO11_DOCTESTATA_1.DO11_FLGESTRATTO, 
        DO11_DOCTESTATA_1.DO11_DATADOC, DO11_DOCTESTATA_1.DO11_DATAREG, 
        DO11_DOCTESTATA_1.DO11_SEZDOC, DO11_DOCTESTATA_1.DO11_ANNODOC
    FROM dbo.DO33_DOCCORPORIF AS DO33_DOCCORPORIF_1 
    INNER JOIN dbo.DO30_DOCCORPO AS DO30_DOCCORPO_1 
        ON DO33_DOCCORPORIF_1.DO33_DITTA_CG18 = DO30_DOCCORPO_1.DO30_DITTA_CG18 
        AND DO33_DOCCORPORIF_1.DO33_NUMREG_CO99 = DO30_DOCCORPO_1.DO30_NUMREG_CO99 
        AND DO33_DOCCORPORIF_1.DO33_PROGRIGA = DO30_DOCCORPO_1.DO30_PROGRIGA 
        AND DO33_DOCCORPORIF_1.DO33_PROGRIF = 1 
    INNER JOIN dbo.DO11_DOCTESTATA AS DO11_DOCTESTATA_1 
        ON DO30_DOCCORPO_1.DO30_DITTA_CG18 = DO11_DOCTESTATA_1.DO11_DITTA_CG18 
        AND DO30_DOCCORPO_1.DO30_NUMREG_CO99 = DO11_DOCTESTATA_1.DO11_NUMREG_CO99 
    LEFT OUTER JOIN dbo.DO52_DOCCORPOLOT AS DO52_DOCCORPOLOT_1 
        ON DO30_DOCCORPO_1.DO30_DITTA_CG18 = DO52_DOCCORPOLOT_1.DO52_DITTA_CG18 
        AND DO30_DOCCORPO_1.DO30_NUMREG_CO99 = DO52_DOCCORPOLOT_1.DO52_NUMREG_CO99 
        AND DO30_DOCCORPO_1.DO30_PROGRIGA = DO52_DOCCORPOLOT_1.DO52_PROGRIGA
    WHERE (DO11_DOCTESTATA_1.DO11_DOCUM_MG36 = 'DF-DDTCLAVCAR')
) AS ESTREMI_DF_DDTCLACAR 
    ON ESTREMI_DF_DDTCLAINV.DO30_DITTA_CG18 = ESTREMI_DF_DDTCLACAR.DO33_DITTA_CG18 
    AND ESTREMI_DF_DDTCLAINV.DO30_NUMREG_CO99 = ESTREMI_DF_DDTCLACAR.DO33_NUMREGRIF_CO99 
    AND ESTREMI_DF_DDTCLAINV.DO30_PROGRIGA = ESTREMI_DF_DDTCLACAR.DO33_PROGRIGARIF_DO30 
    AND (ESTREMI_DF_DDTCLAINV.DO52_PROG = ESTREMI_DF_DDTCLACAR.DO52_PROG 
         OR ESTREMI_DF_DDTCLACAR.DO52_PROG IS NULL)
WHERE (dbo.DO30_DOCCORPO.DO30_INDTIPORIGA = 0) 
  AND (dbo.DO11_DOCTESTATA.DO11_TIPODOC = 1) 
  AND (dbo.DO11_DOCTESTATA.DO11_STIPODOC = 1) 
  AND (dbo.DO11_DOCTESTATA.DO11_TIPOCF_CG44 = 1) 
  AND (SUBSTRING(dbo.DO30_DOCCORPO.DO30_CODART_MG66, 1, 3) IN ('TDP', 'TDL', 'TDR', 'TDF')) 
  AND (SUBSTRING(dbo.DO30_DOCCORPO.DO30_CODART_MG66, 6, 3) IN ('B7-', 'B7M')) 
  AND (dbo.DO11_DOCTESTATA.DO11_DATADOC >= DATEFROMPARTS(2024, 3, 16)) 
  AND (dbo.CO5L_ATTRIBUTIDEN.CO5L_DATA1 IS NOT NULL);
GO

