USE [DBTMV]
GO

/****** Object:  StoredProcedure [dbo].[SPSO_AGGIORNA_STATI_RIGA_GEMINI]    Script Date: 08/09/2026 10:05:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/*
====================================================================================================
-- 1 - DATA/ORA MODIFICA: 2026-07-14 12:00
-- 2 - AUTORE: SOLVERIS - Bandera Marco
-- 3 - DESCRIZIONE E SINTESI TECNICA: 
--     Stored Procedure CORE per l'aggiornamento massivo, automatico e transazionale degli stati 
--     riga Ordine Cliente (CO4H). Il sistema adotta un motore a Ranking (Punteggio) che analizza 
--     le evidenze documentali (ODL, PKL, DDT, AMP) e la cronologia storica (CO4I) per garantire
--     la massima precisione nell'assegnazione dello stato riga.
--
-- ====================================================================================================
-- STORICO REVISIONI:
-- Rev. 1-13: Versioni precedenti consolidate (Ottimizzazione FASE 1, CROSS APPLY, RAISERROR).
-- Rev. 14:   RISOLUZIONE PRODOTTO CARTESIANO. Ristrutturate logiche di evasione multi-livello.
-- Rev. 15:   STESURA DOCUMENTAZIONE IN-CODE. Inserimento della sintesi tecnica per handover.
-- Rev. 16:   GESTIONE FAKE ODL. Introdotta Regola 09B (analisi sequenza 10046->10079->10052). 
-- Rev. 17:   GESTIONE SPEDITO PARZIALE (10084). Evoluzione Regola 13.
-- Rev. 18:   GESTIONE ROLLBACK. Introdotta logica di "paracadute".
-- Rev. 19:   DATA RANKING FASI INTERNE. Uso DO57_DATAMOV per allineamento cronologico MES.
-- Rev. 20:   DATA RANKING RTP E FAKE ODL. Estensione logica DO57_DATAMOV.
-- Rev. 21:   UNIVERSAL ROLLBACK (SAFETY NET). Nuova Regola 99 per righe orfane.
-- Rev. 22:   FIX ROLLBACK RTP (PORTO SICURO). Esclusione 10052 da Regola 99.
-- Rev. 23:   FIX ARTICOLI FITTIZI E PKL. Modificata Regola 11 con CROSS APPLY a 3 livelli.
-- Rev. 24:   ESCLUSIONI AVANZATE (SAFE HARBORS). Estesa la protezione della Regola 99 agli 
--            stati 10079, 10054 e 10068 per evitare regressioni errate.
-- Rev. 25:   DIAGNOSTICA DI ESCLUSIONE FASE 1. Inserito blocco di controllo esplicito per 
--            intercettare i motivi per cui una riga passata in Debug viene scartata a monte.
-- Rev. 26:   INSERIMENTO SAFE HARBOR 10055. Escluso lo stato 10055 (DIBA NON NECESSARIA) 
--            dall'elaborazione di Fase 1, censito nella diagnostica e protetto dal Rollback (Regola 99).
====================================================================================================
*/

CREATE OR ALTER   PROCEDURE [dbo].[SPSO_AGGIORNA_STATI_RIGA_GEMINI]
    @ModalitaDryRun BIT = 0,            -- 1 = Solo simulazione verbosa (DryOut), 0 = Scrittura reale
    @DebugDitta INT = NULL,             
    @DebugNumReg VARCHAR(30) = NULL,    
    @DebugRiga INT = NULL               
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON; -- Garantisce il Rollback immediato in caso di run-time error aborting

    DECLARE @ErroreMessaggio NVARCHAR(4000);
    DECLARE @InizioEsecuzione DATETIME2 = SYSDATETIME();
    DECLARE @FineEsecuzione DATETIME2;
    DECLARE @TargetGUID UNIQUEIDENTIFIER = NULL;

    -- ==========================================
    -- INTERCETTAZIONE PARAMETRI DI DEBUG
    -- ==========================================
    IF @DebugDitta IS NOT NULL AND @DebugNumReg IS NOT NULL AND @DebugRiga IS NOT NULL
    BEGIN
        SELECT @TargetGUID = DO30_GUID 
        FROM dbo.DO30_DOCCORPO WITH (NOLOCK)
        WHERE DO30_DITTA_CG18 = @DebugDitta AND DO30_NUMREG_CO99 = @DebugNumReg AND DO30_PROGRIGA = @DebugRiga;

        IF @TargetGUID IS NULL
        BEGIN
            PRINT 'ATTENZIONE [DIAGNOSTICA]: Riga di test non trovata in DO30_DOCCORPO. Controlla Ditta/NumReg/Riga.';
            RETURN;
        END
        RAISERROR('--- MODALITA FOCUS ATTIVA SULLA RIGA SELEZIONATA ---', 10, 1) WITH NOWAIT;
    END

    BEGIN TRY
        -- ==========================================
        -- FASE 1: MATERIALIZZAZIONE TARGET
        -- ==========================================
        RAISERROR('>> Inizio FASE 1: Materializzazione #TargetGUIDs...', 10, 1) WITH NOWAIT;

        -- Tabella temporanea con collate implicito di sistema per guid ed evitare disallineamenti tempdb
        CREATE TABLE #TargetGUIDs (
            CO4H_GUID UNIQUEIDENTIFIER PRIMARY KEY,
            CO4H_IDSTATO_CO4C INT
        );

        -- Inserimento righe escludendo gli stati terminali e il porto sicuro 10055 (DIBA NON NECESSARIA)
        INSERT INTO #TargetGUIDs (CO4H_GUID, CO4H_IDSTATO_CO4C)
        SELECT CO4H_GUID, CO4H_IDSTATO_CO4C
        FROM dbo.CO4H_STATIATTUALI WITH (NOLOCK)
        WHERE CO4H_IDSTATO_CO4C NOT IN (10053, 10068, 10055); 

        -- Inserimento righe in stato 10053 ma con residuo logico da evadere (es. righe parziali)
        INSERT INTO #TargetGUIDs (CO4H_GUID, CO4H_IDSTATO_CO4C)
        SELECT A.CO4H_GUID, A.CO4H_IDSTATO_CO4C
        FROM dbo.CO4H_STATIATTUALI A WITH (NOLOCK)
        INNER JOIN dbo.DO30_DOCCORPO C WITH (NOLOCK) ON A.CO4H_GUID = C.DO30_GUID
        WHERE A.CO4H_IDSTATO_CO4C = 10053 
          AND NOT EXISTS (SELECT 1 FROM #TargetGUIDs T WITH (NOLOCK) WHERE T.CO4H_GUID = A.CO4H_GUID) 
          AND (
               C.DO30_INDTIPORIGA IN (2, 4, 6, 8) 
               OR EXISTS (
                   SELECT 1 FROM dbo.DO72_DOCCORPOSTATO S WITH (NOLOCK)
                   WHERE S.DO72_DITTA_CG18 = C.DO30_DITTA_CG18 
                     AND S.DO72_NUMREG_CO99 = C.DO30_NUMREG_CO99 
                     AND S.DO72_PROGRIGA = C.DO30_PROGRIGA
                     AND S.DO72_FLGDAEVADERE = 1
               )
          );

        -- Identificazione bypass storici per ODL fittizi (Fake ODL Process)
        CREATE TABLE #HistoryBypass (CO4I_GUID UNIQUEIDENTIFIER PRIMARY KEY);
        
        ;WITH HistoryRank AS (
            SELECT S.CO4I_GUID, S.CO4I_IDSTATO_CO4C,
                   LEAD(S.CO4I_IDSTATO_CO4C, 1) OVER (PARTITION BY S.CO4I_GUID ORDER BY S.CO4I_ID) as S_Next1,
                   LEAD(S.CO4I_IDSTATO_CO4C, 2) OVER (PARTITION BY S.CO4I_GUID ORDER BY S.CO4I_ID) as S_Next2
            FROM dbo.CO4I_STATISTORICO S WITH (NOLOCK)
            INNER JOIN #TargetGUIDs TG ON S.CO4I_GUID = TG.CO4H_GUID
        )
        INSERT INTO #HistoryBypass (CO4I_GUID)
        SELECT DISTINCT CO4I_GUID
        FROM HistoryRank
        WHERE CO4I_IDSTATO_CO4C = 10046 AND S_Next1 = 10079 AND S_Next2 = 10052;

        -- Creazione Struttura Dati Base della Riga
        CREATE TABLE #BaseDatiRiga (
            DO30_GUID UNIQUEIDENTIFIER NOT NULL, 
            DO30_DITTA_CG18_OC INT, DO30_NUMREG_CO99_OC VARCHAR(30) COLLATE DATABASE_DEFAULT, DO30_PROGRIGA_OC INT,
            DO11_NUMDOC_OC INT, DO11_SEZDOC_OC VARCHAR(10) COLLATE DATABASE_DEFAULT, DO30_PROGVISUASTA_OC INT,
            DO11_DATADOC_OC DATETIME, CO4H_IDSTATO_CO4C_ATTUALE INT,
            DO30_DITTA_CG18_ODL INT, DO30_NUMREG_CO99_ODL VARCHAR(30) COLLATE DATABASE_DEFAULT, DO30_PROGRIGA_ODL INT,
            DO11_DOCUM_MG36_ODL VARCHAR(50) COLLATE DATABASE_DEFAULT, DO11_DATADOC_ODL DATETIME,
            FLG_FAKE_ODL BIT DEFAULT 0
        );

        INSERT INTO #BaseDatiRiga
        SELECT 
            C.DO30_GUID, C.DO30_DITTA_CG18, C.DO30_NUMREG_CO99, C.DO30_PROGRIGA,
            T.DO11_NUMDOC, T.DO11_SEZDOC, C.DO30_PROGVISUASTA, T.DO11_DATADOC,
            TG.CO4H_IDSTATO_CO4C,
            ODL.DO30_DITTA_CG18, ODL.DO30_NUMREG_CO99, ODL.DO30_PROGRIGA,
            ODL.DO11_DOCUM_MG36, ODL.DO11_DATADOC,
            CASE WHEN HB.CO4I_GUID IS NOT NULL THEN 1 ELSE 0 END
        FROM #TargetGUIDs TG
        INNER JOIN dbo.DO30_DOCCORPO C WITH (NOLOCK) ON TG.CO4H_GUID = C.DO30_GUID
        INNER JOIN dbo.DO11_DOCTESTATA T WITH (NOLOCK) ON T.DO11_DITTA_CG18 = C.DO30_DITTA_CG18 AND T.DO11_NUMREG_CO99 = C.DO30_NUMREG_CO99
        LEFT JOIN #HistoryBypass HB ON HB.CO4I_GUID = C.DO30_GUID
        OUTER APPLY (
            SELECT TOP 1 
                C_ODL.DO30_DITTA_CG18, C_ODL.DO30_NUMREG_CO99, C_ODL.DO30_PROGRIGA,
                T_ODL.DO11_DOCUM_MG36, T_ODL.DO11_DATADOC
            FROM dbo.DO33_DOCCORPORIF R WITH (NOLOCK)
            INNER JOIN dbo.DO30_DOCCORPO C_ODL WITH (NOLOCK) ON R.DO33_DITTA_CG18 = C_ODL.DO30_DITTA_CG18 AND R.DO33_NUMREG_CO99 = C_ODL.DO30_NUMREG_CO99 AND R.DO33_PROGRIGA = C_ODL.DO30_PROGRIGA
            INNER JOIN dbo.DO31_DOCCORPOORD O_ODL WITH (NOLOCK) ON C_ODL.DO30_DITTA_CG18 = O_ODL.DO31_DITTA_CG18 AND C_ODL.DO30_NUMREG_CO99 = O_ODL.DO31_NUMREG_CO99 AND C_ODL.DO30_PROGRIGA = O_ODL.DO31_PROGRIGA
            INNER JOIN dbo.DO11_DOCTESTATA T_ODL WITH (NOLOCK) ON C_ODL.DO30_DITTA_CG18 = T_ODL.DO11_DITTA_CG18 AND C_ODL.DO30_NUMREG_CO99 = T_ODL.DO11_NUMREG_CO99
            WHERE R.DO33_DITTA_CG18 = C.DO30_DITTA_CG18 
              AND R.DO33_NUMREGRIF_CO99 = C.DO30_NUMREG_CO99 
              AND R.DO33_PROGRIGARIF_DO30 = C.DO30_PROGRIGA
              AND O_ODL.DO31_INDSTATOCONS <> 9
              AND T_ODL.DO11_TIPODOC = 24
            ORDER BY T_ODL.DO11_DATADOC DESC, T_ODL.DO11_NUMDOC DESC
        ) AS ODL
        WHERE T.DO11_TIPODOC = 21 
          AND C.DO30_INDTIPORIGA IN (0, 2, 4, 6, 8)
          AND (@TargetGUID IS NULL OR C.DO30_GUID = @TargetGUID)
        OPTION (FORCE ORDER);

        -- =================================================================================
        -- ENGINE DIAGNOSTICO DI DROPOUT PER DEBUG VARIABILI INIBITE (Aggiornato Rev. 26)
        -- =================================================================================
        IF @TargetGUID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM #BaseDatiRiga WHERE DO30_GUID = @TargetGUID)
        BEGIN
            PRINT '-------------------------------------------------------------------------------------';
            PRINT 'ATTENZIONE: La riga target è stata TROVATA a sistema ma SCARTATA dai filtri della FASE 1.';
            PRINT 'Analisi delle cause di esclusione in corso...';
            PRINT '-------------------------------------------------------------------------------------';

            SELECT 
                C.DO30_GUID,
                T.DO11_TIPODOC AS [Tipo Doc (Atteso 21)],
                C.DO30_INDTIPORIGA AS [Tipo Riga (Attesi 0,2,4,6,8)],
                STATI.CO4H_IDSTATO_CO4C AS [Stato Attuale],
                CASE 
                    WHEN STATI.CO4H_GUID IS NULL THEN 'Mancante in CO4H_STATIATTUALI'
                    WHEN STATI.CO4H_IDSTATO_CO4C = 10068 THEN 'Esclusa: Stato 10068 (Riga Annullata) - Terminale'
                    WHEN STATI.CO4H_IDSTATO_CO4C = 10055 THEN 'Esclusa: Stato 10055 (DIBA NON NECESSARIA) - Porto Sicuro'
                    WHEN STATI.CO4H_IDSTATO_CO4C = 10053 AND C.DO30_INDTIPORIGA NOT IN (2,4,6,8) 
                         AND NOT EXISTS (SELECT 1 FROM dbo.DO72_DOCCORPOSTATO S WITH (NOLOCK) WHERE S.DO72_DITTA_CG18 = C.DO30_DITTA_CG18 AND S.DO72_NUMREG_CO99 = C.DO30_NUMREG_CO99 AND S.DO72_PROGRIGA = C.DO30_PROGRIGA AND S.DO72_FLGDAEVADERE = 1)
                         THEN 'Esclusa: Stato 10053 (Spedito Totale) senza righe inevase in DO72'
                    WHEN T.DO11_TIPODOC <> 21 THEN 'Esclusa: Il documento non è un Impegno Cliente (TipoDoc <> 21)'
                    WHEN C.DO30_INDTIPORIGA NOT IN (0, 2, 4, 6, 8) THEN 'Esclusa: Tipo Riga non ammesso (Descrittiva/Nota pura)'
                    ELSE 'Scarto da verificare (Verificare integrità referenziale DO11/DO30)'
                END AS MotivoEsclusioneFase1
            FROM dbo.DO30_DOCCORPO C WITH (NOLOCK)
            INNER JOIN dbo.DO11_DOCTESTATA T WITH (NOLOCK) ON T.DO11_DITTA_CG18 = C.DO30_DITTA_CG18 AND T.DO11_NUMREG_CO99 = C.DO30_NUMREG_CO99
            LEFT JOIN dbo.CO4H_STATIATTUALI STATI WITH (NOLOCK) ON STATI.CO4H_GUID = C.DO30_GUID
            WHERE C.DO30_GUID = @TargetGUID;

            -- Interrompiamo l'elaborazione del dry-run diagnostico per non sporcare l'output
            IF OBJECT_ID('tempdb..#TargetGUIDs') IS NOT NULL DROP TABLE #TargetGUIDs;
            IF OBJECT_ID('tempdb..#HistoryBypass') IS NOT NULL DROP TABLE #HistoryBypass;
            IF OBJECT_ID('tempdb..#BaseDatiRiga') IS NOT NULL DROP TABLE #BaseDatiRiga;
            RETURN;
        END

        CREATE CLUSTERED INDEX IX_BaseDati_GUID ON #BaseDatiRiga (DO30_GUID);

        -- Materializzazione date DDT collegate per ottimizzazione performance join interne
        CREATE TABLE #DateDDT (
            DO30_DITTA_CG18_OC INT, DO30_NUMREG_CO99_OC VARCHAR(30) COLLATE DATABASE_DEFAULT, DO30_PROGRIGA_OC INT, DATA_DDT DATETIME
        );
        INSERT INTO #DateDDT
        SELECT C_OC.DO30_DITTA_CG18, C_OC.DO30_NUMREG_CO99, C_OC.DO30_PROGRIGA, MAX(T_DDT.DO11_DATADOC)
        FROM dbo.DO30_DOCCORPO C_OC WITH (NOLOCK)
        INNER JOIN dbo.DO33_DOCCORPORIF R1 WITH (NOLOCK) ON C_OC.DO30_DITTA_CG18 = R1.DO33_DITTA_CG18 AND C_OC.DO30_NUMREG_CO99 = R1.DO33_NUMREGRIF_CO99 AND C_OC.DO30_PROGRIGA = R1.DO33_PROGRIGARIF_DO30
        INNER JOIN dbo.DO30_DOCCORPO C_ODL WITH (NOLOCK) ON R1.DO33_DITTA_CG18 = C_ODL.DO30_DITTA_CG18 AND R1.DO33_NUMREG_CO99 = C_ODL.DO30_NUMREG_CO99 AND R1.DO33_PROGRIGA = C_ODL.DO30_PROGRIGA
        INNER JOIN dbo.DO33_DOCCORPORIF R2 WITH (NOLOCK) ON C_ODL.DO30_DITTA_CG18 = R2.DO33_DITTA_CG18 AND C_ODL.DO30_NUMREG_CO99 = R2.DO33_NUMREGRIF_CO99 AND C_ODL.DO30_PROGRIGA = R2.DO33_PROGRIGARIF_DO30
        INNER JOIN dbo.DO30_DOCCORPO C_ORD WITH (NOLOCK) ON R2.DO33_DITTA_CG18 = C_ORD.DO30_DITTA_CG18 AND R2.DO33_NUMREG_CO99 = C_ORD.DO30_NUMREG_CO99 AND R2.DO33_PROGRIGA = C_ORD.DO30_PROGRIGA
        INNER JOIN dbo.DO33_DOCCORPORIF R3 WITH (NOLOCK) ON C_ORD.DO30_DITTA_CG18 = R3.DO33_DITTA_CG18 AND C_ORD.DO30_NUMREG_CO99 = R3.DO33_NUMREGRIF_CO99 AND C_ORD.DO30_PROGRIGA = R3.DO33_PROGRIGARIF_DO30
        INNER JOIN dbo.DO30_DOCCORPO C_DDT WITH (NOLOCK) ON R3.DO33_DITTA_CG18 = C_DDT.DO30_DITTA_CG18 AND R3.DO33_NUMREG_CO99 = C_DDT.DO30_NUMREG_CO99 AND R3.DO33_PROGRIGA = C_DDT.DO30_PROGRIGA
        INNER JOIN dbo.DO11_DOCTESTATA T_DDT WITH (NOLOCK) ON C_DDT.DO30_DITTA_CG18 = T_DDT.DO11_DITTA_CG18 AND C_DDT.DO30_NUMREG_CO99 = T_DDT.DO11_NUMREG_CO99
        WHERE T_DDT.DO11_TIPODOC = 25 AND T_DDT.DO11_STIPODOC = 13
        GROUP BY C_OC.DO30_DITTA_CG18, C_OC.DO30_NUMREG_CO99, C_OC.DO30_PROGRIGA;

        CREATE CLUSTERED INDEX IX_DateDDT ON #DateDDT (DO30_DITTA_CG18_OC, DO30_NUMREG_CO99_OC, DO30_PROGRIGA_OC);

        CREATE TABLE #CandidatiStato (
            DO30_GUID UNIQUEIDENTIFIER NOT NULL, DO11_NUMDOC INT NULL, DO11_SEZDOC VARCHAR(10) COLLATE DATABASE_DEFAULT, 
            DO30_NUMREG_CO99 VARCHAR(30) COLLATE DATABASE_DEFAULT, DO30_PROGRIGA INT NULL, DO30_PROGVISUASTA INT NULL,
            CO4H_IDSTATO_CO4C_ATTUALE INT NOT NULL, CO4H_IDSTATO_CO4C_NEW INT NOT NULL, DataEvento DATETIME NOT NULL,
            OrigineRegola VARCHAR(100) COLLATE DATABASE_DEFAULT, PrioritaSequenza INT DEFAULT 0
        );

        -- ==========================================
        -- FASE 2: APPLICAZIONE REGOLE DI BUSINESS
        -- ==========================================
        RAISERROR('>> Inizio FASE 2: Analisi delle Regole di Punteggio...', 10, 1) WITH NOWAIT;

        -- 1. ODL GENERATO 
        INSERT INTO #CandidatiStato 
        SELECT DO30_GUID, DO11_NUMDOC_OC, DO11_SEZDOC_OC, DO30_NUMREG_CO99_OC, DO30_PROGRIGA_OC, DO30_PROGVISUASTA_OC, CO4H_IDSTATO_CO4C_ATTUALE, 10051, ISNULL(DO11_DATADOC_ODL, DO11_DATADOC_OC), 'Regola 01 - ODL Generato', 1
        FROM #BaseDatiRiga WHERE DO11_DOCUM_MG36_ODL IS NOT NULL; 

        -- 2. IN PRODUZIONE (Fasi interne MES inferiori al limite collaudo)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               10073, ISNULL(FASI.DATA_AVANZAMENTO, ISNULL(B.DO11_DATADOC_ODL, B.DO11_DATADOC_OC)), 'Regola 02 - In Produzione', 2
        FROM #BaseDatiRiga B
        INNER JOIN (
            SELECT D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA, MAX(ADV.DO57_DATAMOV) AS DATA_AVANZAMENTO
            FROM dbo.DO46_DOCCORORDDET D WITH (NOLOCK)
            INNER JOIN dbo.PD12_FASILAVORO P WITH (NOLOCK) ON D.DO46_DITTA_CG18 = P.PD12_DITTA_CG18 AND D.DO46_CODFASE = P.PD12_CODFASE
            LEFT JOIN dbo.DO57_DETAVANZ ADV WITH (NOLOCK) ON D.DO46_DITTA_CG18 = ADV.DO57_DITTA_CG18 AND D.DO46_NUMREG_CO99 = ADV.DO57_NUMREG_CO99 AND D.DO46_PROGRIGA = ADV.DO57_PROGRIGA_DO46 AND D.DO46_PROGDET = ADV.DO57_PROGDET_DO46
            CROSS APPLY (SELECT ISNULL(MAX(CASE WHEN L.DO46_CODFASE = 4031 THEN L.DO46_CODSEQFASE END), MAX(L.DO46_CODSEQFASE)) AS SEQ_LIMITE FROM dbo.DO46_DOCCORORDDET L WITH (NOLOCK) WHERE L.DO46_DITTA_CG18 = D.DO46_DITTA_CG18 AND L.DO46_NUMREG_CO99 = D.DO46_NUMREG_CO99 AND L.DO46_PROGRIGA = D.DO46_PROGRIGA) AS LIM
            WHERE P.PD12_INDTIPOPROV = 0 AND D.DO46_CODSEQFASE < LIM.SEQ_LIMITE AND ISNULL(D.DO46_QTA1CONSOLID, 0) > 0
            GROUP BY D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA
        ) AS FASI ON B.DO30_DITTA_CG18_ODL = FASI.DO46_DITTA_CG18 AND B.DO30_NUMREG_CO99_ODL = FASI.DO46_NUMREG_CO99 AND B.DO30_PROGRIGA_ODL = FASI.DO46_PROGRIGA;

        -- 3. COLLAUDO (Fase Specifica 4031)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               10080, ISNULL(FASI.DATA_AVANZAMENTO, ISNULL(B.DO11_DATADOC_ODL, B.DO11_DATADOC_OC)), 'Regola 03 - Collaudo', 3
        FROM #BaseDatiRiga B
        INNER JOIN (
            SELECT D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA, MAX(ADV.DO57_DATAMOV) AS DATA_AVANZAMENTO
            FROM dbo.DO46_DOCCORORDDET D WITH (NOLOCK)
            INNER JOIN dbo.PD12_FASILAVORO P WITH (NOLOCK) ON D.DO46_DITTA_CG18 = P.PD12_DITTA_CG18 AND D.DO46_CODFASE = P.PD12_CODFASE
            LEFT JOIN dbo.DO57_DETAVANZ ADV WITH (NOLOCK) ON D.DO46_DITTA_CG18 = ADV.DO57_DITTA_CG18 AND D.DO46_NUMREG_CO99 = ADV.DO57_NUMREG_CO99 AND D.DO46_PROGRIGA = ADV.DO57_PROGRIGA_DO46 AND D.DO46_PROGDET = ADV.DO57_PROGDET_DO46
            WHERE P.PD12_INDTIPOPROV = 0 AND D.DO46_CODFASE = 4031 AND D.DO46_QTA1CONSOLID > 0
            GROUP BY D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA
        ) AS FASI ON B.DO30_DITTA_CG18_ODL = FASI.DO46_DITTA_CG18 AND B.DO30_NUMREG_CO99_ODL = FASI.DO46_NUMREG_CO99 AND B.DO30_PROGRIGA_ODL = FASI.DO46_PROGRIGA;

        -- 4. ATTESA INVIO C/LAV (Fasi 4001/4002 esterne)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               IIF(FASI.DO46_CODFASE = 4001, 10069, 10081), ISNULL(FASI.DATA_AVANZAMENTO, ISNULL(B.DO11_DATADOC_ODL, B.DO11_DATADOC_OC)), 
               IIF(FASI.DO46_CODFASE = 4001, 'Regola 04 - Attesa Invio C/Lav (Tratt. 1)', 'Regola 04 - Attesa Invio C/Lav (Tratt. 2)'), 4
        FROM #BaseDatiRiga B
        INNER JOIN (
            SELECT D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA, D.DO46_CODFASE, MAX(ADV.DO57_DATAMOV) AS DATA_AVANZAMENTO
            FROM dbo.DO46_DOCCORORDDET D WITH (NOLOCK)
            INNER JOIN dbo.PD12_FASILAVORO P WITH (NOLOCK) ON D.DO46_DITTA_CG18 = P.PD12_DITTA_CG18 AND D.DO46_CODFASE = P.PD12_CODFASE
            LEFT JOIN dbo.DO57_DETAVANZ ADV WITH (NOLOCK) ON D.DO46_DITTA_CG18 = ADV.DO57_DITTA_CG18 AND D.DO46_NUMREG_CO99 = ADV.DO57_NUMREG_CO99 AND D.DO46_PROGRIGA = ADV.DO57_PROGRIGA_DO46 AND D.DO46_PROGDET = ADV.DO57_PROGDET_DO46
            WHERE P.PD12_INDTIPOPROV = 0 AND D.DO46_CODFASE IN (4001, 4002) AND D.DO46_QTA1CONSOLID > 0
            GROUP BY D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA, D.DO46_CODFASE
        ) AS FASI ON B.DO30_DITTA_CG18_ODL = FASI.DO46_DITTA_CG18 AND B.DO30_NUMREG_CO99_ODL = FASI.DO46_NUMREG_CO99 AND B.DO30_PROGRIGA_ODL = FASI.DO46_PROGRIGA;

        -- 5. TERZISTA 1 (Presenza DDT di Conto Lavoro verificato tramite funzione estesa)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 10070, 
               ISNULL(DDT.DATA_DDT, ISNULL(B.DO11_DATADOC_ODL, B.DO11_DATADOC_OC)), 'Regola 05 - Terzista 1', 5
        FROM #BaseDatiRiga B
        INNER JOIN (
            SELECT DISTINCT DO46_DITTA_CG18, DO46_NUMREG_CO99, DO46_PROGRIGA FROM dbo.DO46_DOCCORORDDET WITH (NOLOCK)
            INNER JOIN dbo.PD12_FASILAVORO WITH (NOLOCK) ON DO46_DITTA_CG18 = PD12_DITTA_CG18 AND DO46_CODFASE = PD12_CODFASE
            WHERE PD12_INDTIPOPROV = 0 AND DO46_CODFASE = 4001 AND DO46_QTA1CONSOLID > 0
        ) AS FASI ON B.DO30_DITTA_CG18_ODL = FASI.DO46_DITTA_CG18 AND B.DO30_NUMREG_CO99_ODL = FASI.DO46_NUMREG_CO99 AND B.DO30_PROGRIGA_ODL = FASI.DO46_PROGRIGA
        LEFT JOIN #DateDDT DDT ON B.DO30_DITTA_CG18_OC = DDT.DO30_DITTA_CG18_OC AND B.DO30_NUMREG_CO99_OC = DDT.DO30_NUMREG_CO99_OC AND B.DO30_PROGRIGA_OC = DDT.DO30_PROGRIGA_OC
        WHERE ISNULL(RTRIM(dbo.SPRT_TMV_MPS_DDT_CLA_ESTREMI(B.DO30_DITTA_CG18_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, 1)), '') <> '';

        -- 6. TERZISTA 2
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 10071, 
               ISNULL(DDT.DATA_DDT, ISNULL(B.DO11_DATADOC_ODL, B.DO11_DATADOC_OC)), 'Regola 06 - Terzista 2', 6
        FROM #BaseDatiRiga B
        INNER JOIN (
            SELECT DISTINCT DO46_DITTA_CG18, DO46_NUMREG_CO99, DO46_PROGRIGA FROM dbo.DO46_DOCCORORDDET WITH (NOLOCK)
            INNER JOIN dbo.PD12_FASILAVORO WITH (NOLOCK) ON DO46_DITTA_CG18 = PD12_DITTA_CG18 AND DO46_CODFASE = PD12_CODFASE
            WHERE PD12_INDTIPOPROV = 0 AND DO46_CODFASE = 4002 AND DO46_QTA1CONSOLID > 0
        ) AS FASI ON B.DO30_DITTA_CG18_ODL = FASI.DO46_DITTA_CG18 AND B.DO30_NUMREG_CO99_ODL = FASI.DO46_NUMREG_CO99 AND B.DO30_PROGRIGA_ODL = FASI.DO46_PROGRIGA
        LEFT JOIN #DateDDT DDT ON B.DO30_DITTA_CG18_OC = DDT.DO30_DITTA_CG18_OC AND B.DO30_NUMREG_CO99_OC = DDT.DO30_NUMREG_CO99_OC AND B.DO30_PROGRIGA_OC = DDT.DO30_PROGRIGA_OC
        WHERE ISNULL(RTRIM(dbo.SPRT_TMV_MPS_DDT_CLA_ESTREMI(B.DO30_DITTA_CG18_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, 1)), '') <> '';

        -- 7. RIENTRO C/LAV (Avanzamenti su fasi 4011/4012)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               IIF(FASI.DO46_CODFASE = 4011, 10074, 10082), ISNULL(FASI.DATA_AVANZAMENTO, ISNULL(B.DO11_DATADOC_ODL, B.DO11_DATADOC_OC)), 
               IIF(FASI.DO46_CODFASE = 4011, 'Regola 07 - Rientro C/Lav (Tratt. 1)', 'Regola 07 - Rientro C/Lav (Tratt. 2)'), 7
        FROM #BaseDatiRiga B
        INNER JOIN (
            SELECT D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA, D.DO46_CODFASE, MAX(ADV.DO57_DATAMOV) AS DATA_AVANZAMENTO
            FROM dbo.DO46_DOCCORORDDET D WITH (NOLOCK)
            INNER JOIN dbo.PD12_FASILAVORO P WITH (NOLOCK) ON D.DO46_DITTA_CG18 = P.PD12_DITTA_CG18 AND D.DO46_CODFASE = P.PD12_CODFASE
            LEFT JOIN dbo.DO57_DETAVANZ ADV WITH (NOLOCK) ON D.DO46_DITTA_CG18 = ADV.DO57_DITTA_CG18 AND D.DO46_NUMREG_CO99 = ADV.DO57_NUMREG_CO99 AND D.DO46_PROGRIGA = ADV.DO57_PROGRIGA_DO46 AND D.DO46_PROGDET = ADV.DO57_PROGDET_DO46
            WHERE P.PD12_INDTIPOPROV = 0 AND D.DO46_CODFASE IN (4011, 4012) AND D.DO46_QTA1CONSOLID > 0
            GROUP BY D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA, D.DO46_CODFASE
        ) AS FASI ON B.DO30_DITTA_CG18_ODL = FASI.DO46_DITTA_CG18 AND B.DO30_NUMREG_CO99_ODL = FASI.DO46_NUMREG_CO99 AND B.DO30_PROGRIGA_ODL = FASI.DO46_PROGRIGA;

        -- 8. SMISTATO C/LAV (Fasi 4021/4022)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               IIF(FASI.DO46_CODFASE = 4021, 10075, 10083), ISNULL(FASI.DATA_AVANZAMENTO, ISNULL(B.DO11_DATADOC_ODL, B.DO11_DATADOC_OC)), 
               IIF(FASI.DO46_CODFASE = 4021, 'Regola 08 - Smistato C/Lav (Tratt. 1)', 'Regola 08 - Smistato C/Lav (Tratt. 2)'), 8
        FROM #BaseDatiRiga B
        INNER JOIN (
            SELECT D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA, D.DO46_CODFASE, MAX(ADV.DO57_DATAMOV) AS DATA_AVANZAMENTO
            FROM dbo.DO46_DOCCORORDDET D WITH (NOLOCK)
            INNER JOIN dbo.PD12_FASILAVORO P WITH (NOLOCK) ON D.DO46_DITTA_CG18 = P.PD12_DITTA_CG18 AND D.DO46_CODFASE = P.PD12_CODFASE
            LEFT JOIN dbo.DO57_DETAVANZ ADV WITH (NOLOCK) ON D.DO46_DITTA_CG18 = ADV.DO57_DITTA_CG18 AND D.DO46_NUMREG_CO99 = ADV.DO57_NUMREG_CO99 AND D.DO46_PROGRIGA = ADV.DO57_PROGRIGA_DO46 AND D.DO46_PROGDET = ADV.DO57_PROGDET_DO46
            WHERE P.PD12_INDTIPOPROV = 0 AND D.DO46_CODFASE IN (4021, 4022) AND D.DO46_QTA1CONSOLID > 0
            GROUP BY D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA, D.DO46_CODFASE
        ) AS FASI ON B.DO30_DITTA_CG18_ODL = FASI.DO46_DITTA_CG18 AND B.DO30_NUMREG_CO99_ODL = FASI.DO46_NUMREG_CO99 AND B.DO30_PROGRIGA_ODL = FASI.DO46_PROGRIGA;

        -- 9. RTP (Fase Finale di Versamento Interno 6000)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               10052, ISNULL(FASI.DATA_AVANZAMENTO, ISNULL(B.DO11_DATADOC_ODL, B.DO11_DATADOC_OC)), 'Regola 09 - RTP', 9
        FROM #BaseDatiRiga B
        INNER JOIN (
            SELECT D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA, MAX(ADV.DO57_DATAMOV) AS DATA_AVANZAMENTO
            FROM dbo.DO46_DOCCORORDDET D WITH (NOLOCK)
            INNER JOIN dbo.PD12_FASILAVORO P WITH (NOLOCK) ON D.DO46_DITTA_CG18 = P.PD12_DITTA_CG18 AND D.DO46_CODFASE = P.PD12_CODFASE
            LEFT JOIN dbo.DO57_DETAVANZ ADV WITH (NOLOCK) ON D.DO46_DITTA_CG18 = ADV.DO57_DITTA_CG18 AND D.DO46_NUMREG_CO99 = ADV.DO57_NUMREG_CO99 AND D.DO46_PROGRIGA = ADV.DO57_PROGRIGA_DO46 AND D.DO46_PROGDET = ADV.DO57_PROGDET_DO46
            WHERE P.PD12_INDTIPOPROV = 0 AND D.DO46_CODFASE = 6000 AND D.DO46_QTA1CONSOLID > 0
            GROUP BY D.DO46_DITTA_CG18, D.DO46_NUMREG_CO99, D.DO46_PROGRIGA
        ) AS FASI ON B.DO30_DITTA_CG18_ODL = FASI.DO46_DITTA_CG18 AND B.DO30_NUMREG_CO99_ODL = FASI.DO46_NUMREG_CO99 AND B.DO30_PROGRIGA_ODL = FASI.DO46_PROGRIGA;

        -- 09B. SALVAGUARDIA RTP PER FAKE ODL PROCESS
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               10052, ISNULL(ADV.DATA_AVANZAMENTO, ISNULL(B.DO11_DATADOC_ODL, B.DO11_DATADOC_OC)), 'Regola 09B - Salvaguardia RTP (Fake ODL Process)', 99 
        FROM #BaseDatiRiga B
        OUTER APPLY (
            SELECT MAX(A.DO57_DATAMOV) AS DATA_AVANZAMENTO FROM dbo.DO57_DETAVANZ A WITH (NOLOCK)
            WHERE A.DO57_DITTA_CG18 = B.DO30_DITTA_CG18_ODL AND A.DO57_NUMREG_CO99 = B.DO30_NUMREG_CO99_ODL AND A.DO57_PROGRIGA_DO46 = B.DO30_PROGRIGA_ODL
        ) AS ADV
        WHERE B.FLG_FAKE_ODL = 1 AND B.DO11_DOCUM_MG36_ODL IS NOT NULL;

        -- 10. PKL (Analisi quantità evase vs quantità riga ordine per distinzione Parziale/Totale)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               IIF(DO30_OC.DO30_QTA1 > ISNULL(PKL.DO30_QTA1_PKL, 0), 10076, 10063), PKL.DATA_PKL, 
               IIF(DO30_OC.DO30_QTA1 > ISNULL(PKL.DO30_QTA1_PKL, 0), 'Regola 10 - PKL Parziale', 'Regola 10 - PKL Totale (Chiuso)'), 10
        FROM #BaseDatiRiga B
        INNER JOIN dbo.DO30_DOCCORPO DO30_OC WITH (NOLOCK) ON B.DO30_DITTA_CG18_OC = DO30_OC.DO30_DITTA_CG18 AND B.DO30_NUMREG_CO99_OC = DO30_OC.DO30_NUMREG_CO99 AND B.DO30_PROGRIGA_OC = DO30_OC.DO30_PROGRIGA
        INNER JOIN ( 
            SELECT DO33.DO33_DITTA_CG18, DO33.DO33_NUMREGRIF_CO99, DO33.DO33_PROGRIGARIF_DO30, SUM(DO30_PKL.DO30_QTA1) AS DO30_QTA1_PKL, MAX(DO11_PKL.DO11_DATADOC) AS DATA_PKL
            FROM dbo.DO11_DOCTESTATA DO11_PKL WITH (NOLOCK)
            INNER JOIN dbo.DO30_DOCCORPO DO30_PKL WITH (NOLOCK) ON DO11_PKL.DO11_DITTA_CG18 = DO30_PKL.DO30_DITTA_CG18 AND DO11_PKL.DO11_NUMREG_CO99 = DO30_PKL.DO30_NUMREG_CO99
            INNER JOIN dbo.DO33_DOCCORPORIF DO33 WITH (NOLOCK) ON DO30_PKL.DO30_DITTA_CG18 = DO33.DO33_DITTA_CG18 AND DO30_PKL.DO30_NUMREG_CO99 = DO33.DO33_NUMREG_CO99 AND DO30_PKL.DO30_PROGRIGA = DO33.DO33_PROGRIGA
            WHERE DO11_PKL.DO11_TIPODOC = 9 AND DO11_PKL.DO11_STIPODOC = 1 
            GROUP BY DO33.DO33_DITTA_CG18, DO33.DO33_NUMREGRIF_CO99, DO33.DO33_PROGRIGARIF_DO30
        ) AS PKL ON PKL.DO33_DITTA_CG18 = B.DO30_DITTA_CG18_OC AND PKL.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND PKL.DO33_PROGRIGARIF_DO30 = B.DO30_PROGRIGA_OC;

        -- 11. ARTICOLI FITTIZI (PKL a rimorchio con 3 livelli di CROSS APPLY referenziale)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               10063, ISNULL(PKL.DATA_PKL, B.DO11_DATADOC_OC), 'Regola 11 - Articoli Fittizi / Descrittive (PKL)', 11
        FROM #BaseDatiRiga B
        INNER JOIN dbo.DO30_DOCCORPO DO30_OC WITH (NOLOCK) ON B.DO30_DITTA_CG18_OC = DO30_OC.DO30_DITTA_CG18 AND B.DO30_NUMREG_CO99_OC = DO30_OC.DO30_NUMREG_CO99 AND B.DO30_PROGRIGA_OC = DO30_OC.DO30_PROGRIGA
        LEFT JOIN dbo.MG66_ANAGRART MG66 WITH (NOLOCK) ON DO30_OC.DO30_DITTA_CG18 = MG66.MG66_DITTA_CG18 AND DO30_OC.DO30_CODART_MG66 = MG66.MG66_CODART
        CROSS APPLY (
            SELECT MAX(DATA_PKL) AS DATA_PKL
            FROM (
                SELECT T1.DO11_DATADOC AS DATA_PKL FROM dbo.DO33_DOCCORPORIF R1 WITH (NOLOCK) INNER JOIN dbo.DO11_DOCTESTATA T1 WITH (NOLOCK) ON R1.DO33_DITTA_CG18 = T1.DO11_DITTA_CG18 AND R1.DO33_NUMREG_CO99 = T1.DO11_NUMREG_CO99 WHERE R1.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND T1.DO11_TIPODOC = 9
                UNION ALL
                SELECT T2.DO11_DATADOC AS DATA_PKL FROM dbo.DO33_DOCCORPORIF R1 WITH (NOLOCK) INNER JOIN dbo.DO33_DOCCORPORIF R2 WITH (NOLOCK) ON R1.DO33_DITTA_CG18 = R2.DO33_DITTA_CG18 AND R1.DO33_NUMREG_CO99 = R2.DO33_NUMREGRIF_CO99 AND R1.DO33_PROGRIGA = R2.DO33_PROGRIGARIF_DO30 INNER JOIN dbo.DO11_DOCTESTATA T2 WITH (NOLOCK) ON R2.DO33_DITTA_CG18 = T2.DO11_DITTA_CG18 AND R2.DO33_NUMREG_CO99 = T2.DO11_NUMREG_CO99 WHERE R1.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND T2.DO11_TIPODOC = 9
                UNION ALL
                SELECT T3.DO11_DATADOC AS DATA_PKL FROM dbo.DO33_DOCCORPORIF R1 WITH (NOLOCK) INNER JOIN dbo.DO33_DOCCORPORIF R2 WITH (NOLOCK) ON R1.DO33_DITTA_CG18 = R2.DO33_DITTA_CG18 AND R1.DO33_NUMREG_CO99 = R2.DO33_NUMREGRIF_CO99 AND R1.DO33_PROGRIGA = R2.DO33_PROGRIGARIF_DO30 INNER JOIN dbo.DO33_DOCCORPORIF R3 WITH (NOLOCK) ON R2.DO33_DITTA_CG18 = R3.DO33_DITTA_CG18 AND R2.DO33_NUMREG_CO99 = R3.DO33_NUMREGRIF_CO99 AND R2.DO33_PROGRIGA = R3.DO33_PROGRIGARIF_DO30 INNER JOIN dbo.DO11_DOCTESTATA T3 WITH (NOLOCK) ON R3.DO33_DITTA_CG18 = T3.DO11_DITTA_CG18 AND R3.DO33_NUMREG_CO99 = T3.DO11_NUMREG_CO99 WHERE R1.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND T3.DO11_TIPODOC = 9
            ) AS X
        ) AS PKL 
        WHERE (DO30_OC.DO30_INDTIPORIGA <> 0 OR ISNULL(MG66.MG66_INDFITTIZIO, 0) <> 0) AND PKL.DATA_PKL IS NOT NULL;

        -- 12. READY TO DELIVERY (Righe fisiche collegate ad Avvisi di Merce Pronta TipoDoc 2)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               10062, ISNULL(AMP.DATA_AMP, B.DO11_DATADOC_OC), 'Regola 12 - Ready to Delivery (AMP)', 12
        FROM #BaseDatiRiga B
        CROSS APPLY (
            SELECT MAX(T.DO11_DATADOC) AS DATA_AMP FROM dbo.DO33_DOCCORPORIF R WITH (NOLOCK) INNER JOIN dbo.DO11_DOCTESTATA T WITH (NOLOCK) ON R.DO33_DITTA_CG18 = T.DO11_DITTA_CG18 AND R.DO33_NUMREG_CO99 = T.DO11_NUMREG_CO99 WHERE R.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND R.DO33_PROGRIGARIF_DO30 = B.DO30_PROGRIGA_OC AND T.DO11_TIPODOC = 2
        ) AS AMP
        WHERE AMP.DATA_AMP IS NOT NULL;

        -- 12B. READY TO DELIVERY (Descrittive/Spese a rimorchio AMP)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               10062, ISNULL(AMP.DATA_AMP, B.DO11_DATADOC_OC), 'Regola 12B - Ready to Delivery (Descrittive/Spese)', 12
        FROM #BaseDatiRiga B
        INNER JOIN dbo.DO30_DOCCORPO DO30_OC WITH (NOLOCK) ON B.DO30_DITTA_CG18_OC = DO30_OC.DO30_DITTA_CG18 AND B.DO30_NUMREG_CO99_OC = DO30_OC.DO30_NUMREG_CO99 AND B.DO30_PROGRIGA_OC = DO30_OC.DO30_PROGRIGA
        LEFT JOIN dbo.MG66_ANAGRART MG66 WITH (NOLOCK) ON DO30_OC.DO30_DITTA_CG18 = MG66.MG66_DITTA_CG18 AND DO30_OC.DO30_CODART_MG66 = MG66.MG66_CODART
        CROSS APPLY (
            SELECT MAX(T.DO11_DATADOC) AS DATA_AMP FROM dbo.DO33_DOCCORPORIF R WITH (NOLOCK) INNER JOIN dbo.DO11_DOCTESTATA T WITH (NOLOCK) ON R.DO33_DITTA_CG18 = T.DO11_DITTA_CG18 AND R.DO33_NUMREG_CO99 = T.DO11_NUMREG_CO99 WHERE R.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND T.DO11_TIPODOC = 2
        ) AS AMP
        WHERE (DO30_OC.DO30_INDTIPORIGA <> 0 OR ISNULL(MG66.MG66_INDFITTIZIO, 0) <> 0) AND AMP.DATA_AMP IS NOT NULL;

        -- 13. SPEDITO / SPEDITO PARZIALE (Righe fisiche con legame a DDT di Spedizione o Carico)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               IIF(DO30_OC.DO30_QTA1 > ISNULL(DDT.TOT_QTA_DDT, 0), 10084, 10053), ISNULL(DDT.DATA_DDT, B.DO11_DATADOC_OC), 
               IIF(DO30_OC.DO30_QTA1 > ISNULL(DDT.TOT_QTA_DDT, 0), 'Regola 13 - Spedito Parziale (DDT)', 'Regola 13 - Spedito Totale (DDT)'), 13
        FROM #BaseDatiRiga B
        INNER JOIN dbo.DO30_DOCCORPO DO30_OC WITH (NOLOCK) ON B.DO30_DITTA_CG18_OC = DO30_OC.DO30_DITTA_CG18 AND B.DO30_NUMREG_CO99_OC = DO30_OC.DO30_NUMREG_CO99 AND B.DO30_PROGRIGA_OC = DO30_OC.DO30_PROGRIGA
        CROSS APPLY (
            SELECT MAX(DATA_DDT) AS DATA_DDT, SUM(QTA_DDT) AS TOT_QTA_DDT
            FROM (
                SELECT T1.DO11_DATADOC AS DATA_DDT, C1.DO30_QTA1 AS QTA_DDT FROM dbo.DO33_DOCCORPORIF R1 WITH (NOLOCK) INNER JOIN dbo.DO11_DOCTESTATA T1 WITH (NOLOCK) ON R1.DO33_DITTA_CG18 = T1.DO11_DITTA_CG18 AND R1.DO33_NUMREG_CO99 = T1.DO11_NUMREG_CO99 INNER JOIN dbo.DO30_DOCCORPO C1 WITH (NOLOCK) ON R1.DO33_DITTA_CG18 = C1.DO30_DITTA_CG18 AND R1.DO33_NUMREG_CO99 = C1.DO30_NUMREG_CO99 AND R1.DO33_PROGRIGA = C1.DO30_PROGRIGA WHERE R1.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND R1.DO33_PROGRIGARIF_DO30 = B.DO30_PROGRIGA_OC AND (T1.DO11_TIPODOC = 1 OR (T1.DO11_TIPODOC = 5 AND T1.DO11_STIPODOC = 2))
                UNION ALL
                SELECT T2.DO11_DATADOC AS DATA_DDT, C2.DO30_QTA1 AS QTA_DDT FROM dbo.DO33_DOCCORPORIF R1 WITH (NOLOCK) INNER JOIN dbo.DO33_DOCCORPORIF R2 WITH (NOLOCK) ON R1.DO33_DITTA_CG18 = R2.DO33_DITTA_CG18 AND R1.DO33_NUMREG_CO99 = R2.DO33_NUMREGRIF_CO99 AND R1.DO33_PROGRIGA = R2.DO33_PROGRIGARIF_DO30 INNER JOIN dbo.DO11_DOCTESTATA T2 WITH (NOLOCK) ON R2.DO33_DITTA_CG18 = T2.DO11_DITTA_CG18 AND R2.DO33_NUMREG_CO99 = T2.DO11_NUMREG_CO99 INNER JOIN dbo.DO30_DOCCORPO C2 WITH (NOLOCK) ON R2.DO33_DITTA_CG18 = C2.DO30_DITTA_CG18 AND R2.DO33_NUMREG_CO99 = C2.DO30_NUMREG_CO99 AND R2.DO33_PROGRIGA = C2.DO30_PROGRIGA WHERE R1.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND R1.DO33_PROGRIGARIF_DO30 = B.DO30_PROGRIGA_OC AND (T2.DO11_TIPODOC = 1 OR (T2.DO11_TIPODOC = 5 AND T2.DO11_STIPODOC = 2))
                UNION ALL
                SELECT T3.DO11_DATADOC AS DATA_DDT, C3.DO30_QTA1 AS QTA_DDT FROM dbo.DO33_DOCCORPORIF R1 WITH (NOLOCK) INNER JOIN dbo.DO33_DOCCORPORIF R2 WITH (NOLOCK) ON R1.DO33_DITTA_CG18 = R2.DO33_DITTA_CG18 AND R1.DO33_NUMREG_CO99 = R2.DO33_NUMREGRIF_CO99 AND R1.DO33_PROGRIGA = R2.DO33_PROGRIGARIF_DO30 INNER JOIN dbo.DO33_DOCCORPORIF R3 WITH (NOLOCK) ON R2.DO33_DITTA_CG18 = R3.DO33_DITTA_CG18 AND R2.DO33_NUMREG_CO99 = R3.DO33_NUMREGRIF_CO99 AND R2.DO33_PROGRIGA = R3.DO33_PROGRIGARIF_DO30 INNER JOIN dbo.DO11_DOCTESTATA T3 WITH (NOLOCK) ON R3.DO33_DITTA_CG18 = T3.DO11_DITTA_CG18 AND R3.DO33_NUMREG_CO99 = T3.DO11_NUMREG_CO99 INNER JOIN dbo.DO30_DOCCORPO C3 WITH (NOLOCK) ON R3.DO33_DITTA_CG18 = C3.DO30_DITTA_CG18 AND R3.DO33_NUMREG_CO99 = C3.DO30_NUMREG_CO99 AND R3.DO33_PROGRIGA = C3.DO30_PROGRIGA WHERE R1.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND R1.DO33_PROGRIGARIF_DO30 = B.DO30_PROGRIGA_OC AND (T3.DO11_TIPODOC = 1 OR (T3.DO11_TIPODOC = 5 AND T3.DO11_STIPODOC = 2))
            ) AS X
        ) AS DDT 
        WHERE DDT.DATA_DDT IS NOT NULL AND NOT (DO30_OC.DO30_QTA1 > ISNULL(DDT.TOT_QTA_DDT, 0) AND B.DO11_DOCUM_MG36_ODL IS NOT NULL);

        -- 13B. SPEDITO (Descrittive/Spese a rimorchio DDT)
        INSERT INTO #CandidatiStato 
        SELECT B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
               10053, ISNULL(DDT.DATA_DDT, B.DO11_DATADOC_OC), 'Regola 13B - Spedito (Descrittive/Spese)', 13
        FROM #BaseDatiRiga B
        INNER JOIN dbo.DO30_DOCCORPO DO30_OC WITH (NOLOCK) ON B.DO30_DITTA_CG18_OC = DO30_OC.DO30_DITTA_CG18 AND B.DO30_NUMREG_CO99_OC = DO30_OC.DO30_NUMREG_CO99 AND B.DO30_PROGRIGA_OC = DO30_OC.DO30_PROGRIGA
        LEFT JOIN dbo.MG66_ANAGRART MG66 WITH (NOLOCK) ON DO30_OC.DO30_DITTA_CG18 = MG66.MG66_DITTA_CG18 AND DO30_OC.DO30_CODART_MG66 = MG66.MG66_CODART
        CROSS APPLY (
            SELECT MAX(DATA_DDT) AS DATA_DDT
            FROM (
                SELECT T1.DO11_DATADOC AS DATA_DDT FROM dbo.DO33_DOCCORPORIF R1 WITH (NOLOCK) INNER JOIN dbo.DO11_DOCTESTATA T1 WITH (NOLOCK) ON R1.DO33_DITTA_CG18 = T1.DO11_DITTA_CG18 AND R1.DO33_NUMREG_CO99 = T1.DO11_NUMREG_CO99 WHERE R1.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND (T1.DO11_TIPODOC = 1 OR (T1.DO11_TIPODOC = 5 AND T1.DO11_STIPODOC = 2))
                UNION ALL
                SELECT T2.DO11_DATADOC AS DATA_DDT FROM dbo.DO33_DOCCORPORIF R1 WITH (NOLOCK) INNER JOIN dbo.DO33_DOCCORPORIF R2 WITH (NOLOCK) ON R1.DO33_DITTA_CG18 = R2.DO33_DITTA_CG18 AND R1.DO33_NUMREG_CO99 = R2.DO33_NUMREGRIF_CO99 AND R1.DO33_PROGRIGA = R2.DO33_PROGRIGARIF_DO30 INNER JOIN dbo.DO11_DOCTESTATA T2 WITH (NOLOCK) ON R2.DO33_DITTA_CG18 = T2.DO11_DITTA_CG18 AND R2.DO33_NUMREG_CO99 = T2.DO11_NUMREG_CO99 WHERE R1.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND (T2.DO11_TIPODOC = 1 OR (T2.DO11_TIPODOC = 5 AND T2.DO11_STIPODOC = 2))
                UNION ALL
                SELECT T3.DO11_DATADOC AS DATA_DDT FROM dbo.DO33_DOCCORPORIF R1 WITH (NOLOCK) INNER JOIN dbo.DO33_DOCCORPORIF R2 WITH (NOLOCK) ON R1.DO33_DITTA_CG18 = R2.DO33_DITTA_CG18 AND R1.DO33_NUMREG_CO99 = R2.DO33_NUMREGRIF_CO99 AND R1.DO33_PROGRIGA = R2.DO33_PROGRIGARIF_DO30 INNER JOIN dbo.DO33_DOCCORPORIF R3 WITH (NOLOCK) ON R2.DO33_DITTA_CG18 = R3.DO33_DITTA_CG18 AND R2.DO33_NUMREG_CO99 = R3.DO33_NUMREGRIF_CO99 AND R2.DO33_PROGRIGA = R3.DO33_PROGRIGARIF_DO30 INNER JOIN dbo.DO11_DOCTESTATA T3 WITH (NOLOCK) ON R3.DO33_DITTA_CG18 = T3.DO11_DITTA_CG18 AND R3.DO33_NUMREG_CO99 = T3.DO11_NUMREG_CO99 WHERE R1.DO33_NUMREGRIF_CO99 = B.DO30_NUMREG_CO99_OC AND (T3.DO11_TIPODOC = 1 OR (T3.DO11_TIPODOC = 5 AND T3.DO11_STIPODOC = 2))
            ) AS X
        ) AS DDT 
        WHERE (DO30_OC.DO30_INDTIPORIGA <> 0 OR ISNULL(MG66.MG66_INDFITTIZIO, 0) <> 0) AND DDT.DATA_DDT IS NOT NULL;

        -- 99. UNIVERSAL ROLLBACK (SAFETY NET / PARACADUTE RIGHETTA ORFANA)
        -- Esclusione esplicita per i SAFE HARBORS consolidati (10052, 10079, 10054, 10068) 
        -- e il nuovo stato 10055 (DIBA NON NECESSARIA) integrato nella Rev. 26
        INSERT INTO #CandidatiStato 
        SELECT 
            B.DO30_GUID, B.DO11_NUMDOC_OC, B.DO11_SEZDOC_OC, B.DO30_NUMREG_CO99_OC, B.DO30_PROGRIGA_OC, B.DO30_PROGVISUASTA_OC, B.CO4H_IDSTATO_CO4C_ATTUALE, 
            HIST.CO4I_IDSTATO_CO4C, HIST.CO4I_DATAGG, 'Regola 99 - Ripristino stato (Documento orfano/cancellato)', 0 
        FROM #BaseDatiRiga B
        CROSS APPLY (
            SELECT TOP 1 S.CO4I_IDSTATO_CO4C, S.CO4I_DATAGG
            FROM dbo.CO4I_STATISTORICO S WITH (NOLOCK)
            WHERE S.CO4I_GUID = B.DO30_GUID AND S.CO4I_IDSTATO_CO4C <> B.CO4H_IDSTATO_CO4C_ATTUALE
              AND S.CO4I_IDSTATO_CO4C NOT IN (10051, 10073, 10072, 10080, 10069, 10081, 10070, 10071, 10074, 10082, 10075, 10083) 
            ORDER BY S.CO4I_ID DESC
        ) AS HIST
        WHERE B.CO4H_IDSTATO_CO4C_ATTUALE >= 10051
          AND B.CO4H_IDSTATO_CO4C_ATTUALE NOT IN (10052, 10079, 10054, 10068, 10055) -- SAFE HARBORS
          AND NOT EXISTS (SELECT 1 FROM #CandidatiStato C WHERE C.DO30_GUID = B.DO30_GUID);

        -- ==========================================
        -- FASE 3: ELABORAZIONE CLASSIFICA RANKING
        -- ==========================================
        RAISERROR('>> Inizio FASE 3: Risoluzione conflitti e calcolo Ranking (Classifica)...', 10, 1) WITH NOWAIT;
        
        WITH ClassificaStati AS (
            SELECT DO30_GUID, DO11_NUMDOC, DO11_SEZDOC, DO30_NUMREG_CO99, DO30_PROGRIGA, DO30_PROGVISUASTA, CO4H_IDSTATO_CO4C_ATTUALE, CO4H_IDSTATO_CO4C_NEW, OrigineRegola, DataEvento, PrioritaSequenza,
                   ROW_NUMBER() OVER (PARTITION BY DO30_GUID ORDER BY DataEvento DESC, PrioritaSequenza DESC) AS Rn
            FROM #CandidatiStato
        )
        SELECT * INTO #ClassificaStati FROM ClassificaStati;
        
        -- ==========================================
        -- FASE 4: OUTPUT DIAGNOSTICO VERBOSO O COMMIT
        -- ==========================================
        RAISERROR('>> Inizio FASE 4: Output DryOut o Esecuzione Transazionale...', 10, 1) WITH NOWAIT;
        
        IF @ModalitaDryRun = 1
        BEGIN
            -- MODALITÀ DRYOUT VERBOSA (Nessuna modifica a DB)
            IF @TargetGUID IS NOT NULL
            BEGIN
                -- Output dettagliato per singola riga forzata in debug per tracciabilità regole
                SELECT DO30_GUID AS [GUID Riga], Rn AS [Ranking], DO11_NUMDOC AS [Num. Doc. OC], DO11_SEZDOC AS [Sez. Doc.], DO30_NUMREG_CO99 AS [Num. Reg. OC], DO30_PROGRIGA AS [Prog. Riga Int.], DO30_PROGVISUASTA AS [Prog. Vis. OC], OrigineRegola AS [Regola Valutata], DataEvento, CO4H_IDSTATO_CO4C_ATTUALE AS [Stato Attuale], CO4H_IDSTATO_CO4C_NEW AS [Nuovo Stato]
                FROM #ClassificaStati WITH (NOLOCK) ORDER BY Rn;
            END
            ELSE
            BEGIN
                -- Output massivo delle righe che cambierebbero stato a sistema
                SELECT OrigineRegola AS [Regola Vincente], DO11_NUMDOC AS [Num. Doc. OC], DO11_SEZDOC AS [Sez. Doc.], DO30_NUMREG_CO99 AS [Num. Reg. OC], DO30_PROGRIGA AS [Prog. Riga Int.], DO30_PROGVISUASTA AS [Prog. Vis. OC], DataEvento, CO4H_IDSTATO_CO4C_ATTUALE AS [Stato Attuale], CO4H_IDSTATO_CO4C_NEW AS [Nuovo Stato Proposto]
                FROM #ClassificaStati WITH (NOLOCK) WHERE Rn = 1 AND CO4H_IDSTATO_CO4C_ATTUALE <> CO4H_IDSTATO_CO4C_NEW ORDER BY DataEvento DESC, [Num. Doc. OC], [Prog. Vis. OC];
            END
        END
        ELSE
        BEGIN
            -- SCRITTURA REALE TRANSAZIONALE PROTEGGERE DA BLOCCHI IN LETTURA
            IF @TargetGUID IS NOT NULL 
            BEGIN
                PRINT 'Esecuzione Reale bloccata cautelativamente: Parametri di DEBUG attivi. Disabilitare i filtri riga per scrivere.';
            END
            ELSE
            BEGIN
                BEGIN TRANSACTION;
                
                UPDATE ATTUALI 
                SET ATTUALI.CO4H_IDSTATO_CO4C = WINNER.CO4H_IDSTATO_CO4C_NEW 
                FROM dbo.CO4H_STATIATTUALI AS ATTUALI 
                INNER JOIN #ClassificaStati AS WINNER ON ATTUALI.CO4H_GUID = WINNER.DO30_GUID 
                WHERE WINNER.Rn = 1 AND ATTUALI.CO4H_IDSTATO_CO4C <> WINNER.CO4H_IDSTATO_CO4C_NEW;
                
                COMMIT TRANSACTION;
                RAISERROR('>> Transazione completata con successo a Database.', 10, 1) WITH NOWAIT;
            END
        END

        SET @FineEsecuzione = SYSDATETIME();
        PRINT 'Tempo elaborazione complessivo: ' + CAST(DATEDIFF(MILLISECOND, @InizioEsecuzione, @FineEsecuzione) AS VARCHAR) + ' ms.';

    END TRY
    BEGIN CATCH
        -- Gestione Rollback sicuro
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        SET @ErroreMessaggio = ERROR_MESSAGE();
        PRINT '!!! ERRORE CRITICO RILEVATO: ' + @ErroreMessaggio;
        THROW;
    END CATCH
    
    -- Cleanup Temp Tables
    IF OBJECT_ID('tempdb..#TargetGUIDs') IS NOT NULL DROP TABLE #TargetGUIDs;
    IF OBJECT_ID('tempdb..#HistoryBypass') IS NOT NULL DROP TABLE #HistoryBypass;
    IF OBJECT_ID('tempdb..#BaseDatiRiga') IS NOT NULL DROP TABLE #BaseDatiRiga;
    IF OBJECT_ID('tempdb..#DateDDT') IS NOT NULL DROP TABLE #DateDDT;
    IF OBJECT_ID('tempdb..#CandidatiStato') IS NOT NULL DROP TABLE #CandidatiStato;
    IF OBJECT_ID('tempdb..#ClassificaStati') IS NOT NULL DROP TABLE #ClassificaStati;
END;
GO

